In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv("sabbir.csv")

In [3]:
df


area    price
0   1500   50000
1   1700   60000
2   2000   65000
3   2500   70000
4   3000   75000
5   3500   80000
6   5000  100000
7   5500  110000
8   6000  125000

In [4]:
df.isnull().sum()

area     0
price    0
dtype: int64

In [5]:
sabbir= df.iloc[:,:-1].values
sakib=df.iloc[:,-1].values 

In [6]:
sabbir

array([[1500],
       [1700],
       [2000],
       [2500],
       [3000],
       [3500],
       [5000],
       [5500],
       [6000]], dtype=int64)

In [7]:
sakib

array([ 50000,  60000,  65000,  70000,  75000,  80000, 100000, 110000,
       125000], dtype=int64)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
xtrain,xtest,ytrain,ytest=train_test_split(sabbir,sakib,test_size=.30,random_state=1)

In [10]:
xtrain

array([[5500],
       [1700],
       [1500],
       [3000],
       [2500],
       [3500]], dtype=int64)

In [11]:
xtest

array([[6000],
       [2000],
       [5000]], dtype=int64)

In [12]:
ytest

array([125000,  65000, 100000], dtype=int64)

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
reg=LinearRegression()

In [15]:
reg.fit(xtrain,ytrain)

LinearRegression()

In [16]:
reg.predict(xtest)

array([116809.52380952,  60884.46526151, 102828.25917252])

In [17]:
reg.predict([[4400]])

array([94439.50039032])

In [20]:
reg.predict([[5400]])

array([108420.76502732])